trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    variables:
      RestoreBuildProjects: '**/*.csproj'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.0'
      inputs:
        version: 3.0.x
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(RestoreBuildProjects)'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        modifyOutputPath: False
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    pool:
      vmImage: windows-latest
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@3
            displayName: 'Deploy Azure App Service'
            inputs:
              azureSubscription: 'paxschedule - 1 - Service Endpoint'
              WebAppName: PAXSchedule
              Package: '$(Pipeline.Workspace)\drop\*.zip'
              TakeAppOfflineFlag: true
              UseWebDeploy: true
              RemoveAdditionalFilesFlag: true
              ExcludeFilesFromAppDataFlag: true
              RenameFilesFlag: true
